name: Upload to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-central-1

      - name: Set up SSH key
        run: |
          echo "${{ secrets.PRIVATE_SSH_KEY }}" > /tmp/key.pem
          chmod 600 /tmp/key.pem
          echo -e "Host 3.121.189.240\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        env:
          PRIVATE_SSH_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
    
      - name: Upload index.html
        run: |
          scp -i /tmp/key.pem index.html ubuntu@3.121.189.240:/usr/share/nginx/html/
      
      - name: Clean up SSH key
        run: rm /tmp/key.pem
