name: Upload to EC2
on: [push]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      deploy_file: "index.html"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up credentials
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: "$deploy_file"
          TARGET: ${{ secrets.TARGET_DIR }}
