name: Upload to EC2
on: [push]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up credentials
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          REMOTE_HOST: 18.195.149.80
          REMOTE_USER: "ubuntu"
          SOURCE: "index.html"
          TARGET_DIR: "/var/www/html"
