name: Upload to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-central-1


      - name: Set up credentials
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          REMOTE_HOST: 18.195.149.80
          REMOTE_USER: "ubuntu"
          SOURCE: "index.html"
          TARGET_DIR: "/var/www/html"
          
          AFTER_SCRIPT: |
            ssh -o StrictHostKeyChecking=no -i /tmp/key.pem ubuntu@18.195.149.80 'if [ -f "/var/www/html/index.nginx-debian.html" ]; then
              sudo rm /var/www/html/index.nginx-debian.html 
            fi'

            if [ -f "index.html" ]; then
              sudo mv index.html /var/www/html/
            fi   



