name: Upload to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-central-1

      - name: Set up SSH key
        run: |
          echo "${{ secrets.PRIVATE_SSH_KEY }}" > /tmp/key.pem
          chmod 600 /tmp/key.pem
        env:
          PRIVATE_SSH_KEY: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Create SSH config
        run: |
          mkdir -p /home/runner/.ssh
          echo "Host your-ec2-instance-ip" > /home/runner/.ssh/config
          echo "  IdentityFile /tmp/key.pem" >> /home/runner/.ssh/config
          chmod 600 /home/runner/.ssh/config
    
      - name: Upload index.html
        run: |
          run: scp -o StrictHostKeyChecking=no -i /tmp/key.pem index.html ubuntu@3.121.189.240:/usr/share/nginx/html/
      
      - name: Clean up SSH key
        run: rm /tmp/key.pem
